### ISSUE TITLE
telemetry documentation does not property have doumented

### ISSUE THREAD

**Issue by mckaygerhard** [librespeed/speedtest#260]
## Description

telemetry documentation has errors.. by example _"url_telemetry: path to telemetry.php or replacement ->    Default: telemetry/telemetry.php"_ but the default are "results/telemetry.php"

sqlite and postgres does not work due must be restarted .. and mysql just work as described in #259  the problem are due only the mysql are used property and sqlite and postgresql just uses PDO.. 

seems same as suicceed for https://github.com/librespeed/speedtest/issues/182 

you noted https://github.com/librespeed/speedtest/issues/75#issuecomment-474249125 that sqlite does not work and in php-cgi or php-fpm or php-mod-apache ...  only after restart the webserver of any other process that uses the db PDO backend

## Server

* debian 9 tested with apache2 and php 7.0 
* also in debian 7 with apache2 and php 7.3 backported 
* also in devuan ascii with lighttpd and php 7.4 backported 
* also in centos 7 with httpd 2.4 apache2

## Client
firefox lasted

## Expected behaviour

working shareable area

## Steps to reproduce

```
apt-get install php apache2 git wget nano curl php-sqlite

git clone https://github.com/librespeed/speedtest speedtest

edit telemetry settings and shoose sqlite

chown -R www-data:www-data /var/www
```

source code uses direct mysql module for mysql but for postgres or sqlite only uses PDO, thats are the errors:

## espected behaviour

property document the configuration **i can help on that and send a pull request**

## logs

```
2019-12-02 12:32:51: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught PDOException: could not find driver in /var/www/webapps/speedtest/results/telemetry.php:44
2019-12-02 12:32:51: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2019-12-02 12:32:51: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/webapps/speedtest/results/telemetry.php(44): PDO->__construct('pdo_sqlite:spee...')
2019-12-02 12:32:51: (mod_fastcgi.c.2543) FastCGI-stderr: #1 {main}
2019-12-02 12:32:51: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/webapps/speedtest/results/telemetry.php on line 44
2019-12-02 12:39:36: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error:  Uncaught PDOException: could not find driver in /var/www/webapps/speedtest/results/telemetry.php:44
2019-12-02 12:39:36: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2019-12-02 12:39:36: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /var/www/webapps/speedtest/results/telemetry.php(44): PDO->__construct('sqlite://speedt...')
2019-12-02 12:39:36: (mod_fastcgi.c.2543) FastCGI-stderr: #1 {main}
2019-12-02 12:39:36: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /var/www/webapps/speedtest/results/telemetry.php on line 44
```

**Comment by adolfintel** [comment]
>"url_telemetry: path to telemetry.php or replacement -> Default: telemetry/telemetry.php" but the default are "results/telemetry.php"

Fixed. Thanks for noticing.


Not sure what you're trying to say about the PDO thing, the documentation [clearly says](https://github.com/librespeed/speedtest/wiki/Installation-(PHP)) that it's using PDO for sqlite and postgre, and mysqli for mysql.

**Comment by mckaygerhard** [comment]
why mysql are direct adn postgres/sqlite are with PDO ? that the point!

**Comment by adolfintel** [comment]
There isn't a specific reason. When I wrote the mysql code I didn't know about PDO yet, that's all
